<a href="https://colab.research.google.com/github/vyolete/q4/blob/master/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from dateutil.parser import parse 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
plt.rcParams.update({'figure.figsize': (10, 7), 'figure.dpi': 120})

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
clientes=pd.read_csv("https://raw.githubusercontent.com/vyolete/q4/master/Copy%20of%20DB%20Customers%20Masivo%201%20Latam%20Q4.csv",encoding='ISO-8859-1')

In [27]:
clientes.shape

(4296, 21)

In [28]:
clientes.columns

Index(['Primary Deployment Id', 'Industry', 'Primary Account Name',
       'Sales Sub Territory Name', 'First Name', 'Last Name', 'Title',
       'Mailing Street', 'Mailing City', 'Mailing Country (text only)',
       'Phone', 'Mobile', 'Fax', 'Score', 'Email', 'Total Licenses Purchased',
       'Total Licenses Activated', 'Over Install', 'Last Login',
       'Last Activity', 'Account Owner'],
      dtype='object')

In [32]:
cuentas=pd.DataFrame(clientes['Primary Account Name'].value_counts())


cuentas.head

<bound method NDFrame.head of                                                     Primary Account Name
LINALCA INFORMATICA S A                                               54
Banco Davivienda (Panama) SA                                          52
ARUS TECNOLOGIA                                                       45
ASOCIACION NACIONAL DE FUNCIONARIOS DEL MINISTE...                    29
Ross University School of Veterinary Medicine                         26
...                                                                  ...
Grupo Financiero Inbursa, S.A.B. de C.V.                               1
Aromáticos La Victoria, S.A. de C.V.                                   1
KRAUSS MAFFEI CORPORATION                                              1
Servicios Especializados en Distribución Comerc...                     1
Hilti Chile Limitada                                                   1

[2452 rows x 1 columns]>

In [0]:
prueba=pd.crosstab(index=clientes['Primary Account Name'],
            columns=clientes['Mailing Country (text only)'], margins=True)

In [36]:
prueba.columns

Index(['Antigua and Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belize',
       'Bermuda', 'Bolivia, Plurinational State of', 'Brazil',
       'Cayman Islands', 'Chile', 'Colombia', 'Costa Rica',
       'Dominican Republic', 'Ecuador', 'El Salvador', 'France', 'Guatemala',
       'Haiti', 'Honduras', 'India', 'Italy', 'Jamaica', 'Mexico', 'Nicaragua',
       'Nigeria', 'Panama', 'Paraguay', 'Peru', 'Poland', 'Puerto Rico',
       'Saint Kitts and Nevis', 'Spain', 'Suriname', 'Switzerland',
       'Trinidad and Tobago', 'United Kingdom', 'United States',
       'United States Minor Outlying Islands', 'Uruguay',
       'Venezuela, Bolivarian Republic of', 'All'],
      dtype='object', name='Mailing Country (text only)')

In [38]:
prueba['All'].unique()

array([   1,    2,    4,   17,    6,   45,    3,   29,    8,    7,    5,
         16,   14,    9,   52,   10,   19,   25,   13,   11,   15,   12,
         54,   26,   20,   18, 4264])

In [39]:
prueba

Mailing Country (text only)   Antigua and Barbuda  ...   All
Primary Account Name                               ...
3M El Salvador S.A. de C.V.                     0  ...     1
3M Guatemala, S.A.                              0  ...     1
3M Honduras, S.A.                               0  ...     1
3M Panama S.A.                                  0  ...     1
3M Peru S.A.                                    0  ...     1
...                                           ...  ...   ...
symptai consulanting limited                    0  ...     1
tcl mexico                                      0  ...     1
veerabhadra aradya aradya                       0  ...     1
xpcolombia                                      0  ...     1
All                                             2  ...  4264

[2448 rows x 41 columns]

In [0]:
prueba.to_csv("preuba")